---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Java."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "Hello from local pubsub topic"
    Topic: "/topic/local/pubsub"
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.example.JavaLocalPubSub:pubsub:1:
          policyDescription: Allows access to publish and subscribe to topic /topic/local/pubsub.
          operations:
            - aws.greengrass#SubscribeToTopic
            - aws.greengrass#PublishToTopic
          resources:
            - "/topic/local/pubsub"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/LocalPubSub-1.0.0.jar"
    Lifecycle:
      Run: "java -cp {artifacts:path}/LocalPubSub-1.0.0.jar com.localpubsub.App {configuration:/Topic} {configuration:/Message}"
