---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Python\n"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Config:
      Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "{FILE_PATH}/{COMPONENT_NAME}/{COMPONENT_VERSION}/HelloWorld.zip"
          Unarchive: ZIP
      Lifecycle:
        Run: "python3 -u {artifacts:decompressedPath}/HelloWorld/main.py {configuration:/Message}"